version: "2.6"
services:

  backend:
    image: backend
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  frontend:
    image: frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - 8081:8081